/*
 * BatteryMonitor.h
 *
 *  Created on: Nov 5, 2016
 *      Author: Josh
 */

#ifndef APPLICATION_BATTERYMONITOR_H_
#define APPLICATION_BATTERYMONITOR_H_



#define BATT_GAUGE_REG_MODE 0x00
#define BATT_GAUGE_REG_CTRL 0x01
#define BATT_GAUGE_REG_CHARGE_LOW 0x02
#define BATT_GAUGE_REG_CHARGE_HIGH 0x03
#define BATT_GAUGE_REG_COUNTER_LOW 0x04
#define BATT_GAUGE_REG_COUNTER_HIGH 0x05
#define BATT_GAUGE_REG_CURRENT_LOW 0x06
#define BATT_GAUGE_REG_CURRENT_HIGH 0x07
#define BATT_GAUGE_REG_VOLTAGE_LOW 0x08
#define BATT_GAUGE_REG_VOLTAGE_HIGH 0x09
#define BATT_GAUGE_REG_TEMP_LOW 0x0A
#define BATT_GAUGE_REG_TEMP_HIGH 0x0B

 // Enum of message types
typedef enum {
	BATMONITOR_MSG_UPDATE_BAT_VALUES,
	BATMONITOR_MSG_RED_LED_OFF,
	BATMONITOR_MSG_GRN_LED_OFF,
	BATMONITOR_MSG_BLU_LED_OFF,
	BATMONITOR_MSG_RED_LED_ON,
	BATMONITOR_MSG_GRN_LED_ON,
	BATMONITOR_MSG_BLU_LED_ON,
} batMonitor_msg_types_t;

extern void enqueueBatMonitortTaskMsg(batMonitor_msg_types_t msgType);

#endif /* APPLICATION_BATTERYMONITOR_H_ */
